### ISSUE TITLE
Automatic spacing based on time of entries

### ISSUE THREAD

**Issue by bbrosius** [softmarshmallow/flutter-timeline#11]
I'm curious if there is a way to make the timeline adjust where items appear based on the gap in time between events. For example items that are five minutes apart might be spaced 5 px. Whereas items an hour apart would have more spacing say 20 px. 

If this isn't something that can be done automatically in the library, I'd be any thoughts you had on how to manually do this in the app using the library.

**Comment by softmarshmallow** [comment]
quick answer:
if you are trying to visualize time gap,  you can set itemgap to zero, and give TimelineEvent#content's padding by the size by interval you want.

also, problem that your having is not quite general. which means it might not be right to implement in the package itself.
if you suggest any references (screen, mockup, or service) i'de be glad to implement it as in-the-box. (if it is general problem)

p.s other solution: // or since timeline view is internally just a listview, you can pass seperator builder to it, having different sized diver by the time interval.

**Comment by softmarshmallow** [comment]
I'll close this issue. if you have any other question, please re-open it or create a new one. thanks

**Comment by bbrosius** [comment]
@softmarshmallow Thanks for the help. I was able to get this largely working using a separator builder. I noticed two things not sure if they're bugs or not. When I start supplying a separator builder for some reason the line starts drawing on top of the first indicator dot instead of underneath it. If I comment out the separator builder it worked as normal. Also when using the separator builder the lines are broken as they don't seem to take all of the space of the separator. I've attached a screenshot. I plan to continue to play around if I figure out a fix would you be interested in a pull request?

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-09 at 15 39 14](https://user-images.githubusercontent.com/3709725/92645694-3b871e00-f2b3-11ea-82fa-1276665bbf6a.png)

**Comment by softmarshmallow** [comment]
@bbrosius sure i’de be happy to. 
seperator builder might be a bug, since adding a padding to each item instead using seperator builder will work. 

however, again, Id’e be happy to take your PR and add as contributor

Ill take a look on this issue in this weekend

**Comment by softmarshmallow** [comment]
@bbrosius haven't heard you for a while. would it be ok to close this issue? or shall i wait for the PR

**Comment by bbrosius** [comment]
@softmarshmallow Sorry didn't manage to get to it last week. I still plan to submit a PR but we can close this issue.
